name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./API/package-lock.json
    - run: npm ci
      working-directory: ./API
    - run: npm run build --if-present
      working-directory: ./API
    - run: npm test
      working-directory: ./API
